export { default as DashboardPage } from "./DashboardPage";
export { default as EmpresasPage } from "./EmpresasPage";
export { default as EmpresaFormPage } from "./EmpresaFormPage";
export { default as FiliaisPage } from "./FiliaisPage";
export { default as InscricoesEstaduaisPage } from "./InscricoesEstaduaisPage";
export { default as UsuariosPage } from "./UsuariosPage";
export { default as UsuarioFormPage } from "./UsuarioFormPage";
export { default as PerfisPage } from "./PerfisPage";
export { default as ConfiguracoesPage } from "./ConfiguracoesPage";
